import os
import sys
import glob
import json
import requests
import yaml
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
import google.generativeai as genai

# ==============================================================================
# 1. Environment & Credentials Setup
# ==============================================================================
BLOG_ID = os.environ.get("BLOGGER_BLOG_ID")
CLIENT_ID = os.environ.get("BLOGGER_CLIENT_ID")
CLIENT_SECRET = os.environ.get("BLOGGER_CLIENT_SECRET")
REFRESH_TOKEN = os.environ.get("BLOGGER_REFRESH_TOKEN")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not all([BLOG_ID, CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN, GEMINI_API_KEY]):
    print("Error: One or more required environment variables are missing.")
    sys.exit(1)

# Configure Gemini API
genai.configure(api_key=GEMINI_API_KEY)

# Build Blogger Service using Refresh Token
def get_blogger_service():
    creds = Credentials(
        token=None,
        refresh_token=REFRESH_TOKEN,
        token_uri="https://oauth2.googleapis.com/token",
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        scopes=["https://www.googleapis.com/auth/blogger"]
    )
    if not creds.valid:
        creds.refresh(Request())
    return build("blogger", "v3", credentials=creds)


# ==============================================================================
# 2. Markdown & Frontmatter Parsing
# ==============================================================================
def parse_markdown_file(filepath):
    """
    Extracts YAML frontmatter and content body from a Markdown file.
    """
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    frontmatter = {}
    body = content

    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            try:
                frontmatter = yaml.safe_load(parts[1]) or {}
                body = parts[2].strip()
            except yaml.YAMLError as e:
                print(f"Warning: Failed to parse YAML frontmatter in {filepath}: {e}")

    return frontmatter, body


# ==============================================================================
# 3. Gemini Content Transformation
# ==============================================================================
def transform_markdown_to_html(markdown_text, title):
    """
    Converts raw Markdown into clean, well-structured HTML optimized for Blogger.
    """
    model = genai.GenerativeModel("gemini-3.6-flash")

    prompt = f"""
You are an expert digital content editor converting Markdown into clean HTML for a Blogger post.

Target Title: {title}

Instructions:
1. Convert the provided Markdown body into modern, responsive, semantic HTML suitable for Blogger.
2. Maintain all original core points and voice, but polish readability, typography spacing, and inline layout where beneficial.
3. Wrap headers in standard HTML tags (<h2>, <h3>). Use <p>, <ul>, <ol>, <li>, <blockquote>, and <strong> tags appropriately.
4. DO NOT wrap the output in ```html ``` code fences or output any introductory/concluding conversational text. Output ONLY the raw HTML body.

Markdown Body:
{markdown_text}
"""

    response = model.generate_content(prompt)
    html_content = response.text.strip()

    # Strip code block wrappers if generated by model
    if html_content.startswith("```html"):
        html_content = html_content[7:]
    if html_content.startswith("```"):
        html_content = html_content[3:]
    if html_content.endswith("```"):
        html_content = html_content[:-3]

    return html_content.strip()


# ==============================================================================
# 4. Blogger API Distribution
# ==============================================================================
def publish_post(service, title, html_content, tags, status):
    """
    Posts the processed HTML to Google Blogger.
    """
    is_draft = True if status.lower() == "draft" else False

    body = {
        "kind": "blogger#post",
        "title": title,
        "content": html_content,
        "labels": tags if isinstance(tags, list) else []
    }

    try:
        request = service.posts().insert(
            blogId=BLOG_ID,
            body=body,
            isDraft=is_draft
        )
        response = request.execute()
        
        post_url = response.get("url", "Draft saved (no public URL yet)")
        status_label = "DRAFT" if is_draft else "PUBLISHED"
        print(f"[{status_label}] Successfully created post: '{title}'")
        print(f"URL: {post_url}\n")
        return response

    except Exception as e:
        print(f"Error publishing post '{title}': {e}")
        return None


# ==============================================================================
# 5. Main Execution Flow
# ==============================================================================
def main():
    # Target directory or pass path as command argument
    target_dir = sys.argv[1] if len(sys.argv) > 1 else "WritingFactory/Mindset"

    print(f"Searching for Markdown files in: {target_dir}")
    md_files = glob.glob(f"{target_dir}/**/*.md", recursive=True) + glob.glob(f"{target_dir}/*.md")
    md_files = list(set(md_files)) # deduplicate

    if not md_files:
        print(f"No Markdown files found in {target_dir}.")
        return

    print(f"Found {len(md_files)} file(s) to process.\n")
    service = get_blogger_service()

    for filepath in md_files:
        print(f"--- Processing: {filepath} ---")
        frontmatter, body = parse_markdown_file(filepath)

        title = frontmatter.get("title", os.path.basename(filepath).replace(".md", ""))
        tags = frontmatter.get("tags", [])
        status = frontmatter.get("status", "publish")

        print(f"Title: {title}")
        print(f"Status: {status}")
        print(f"Tags: {tags}")

        print("Transforming Markdown to HTML via Gemini...")
        html_content = transform_markdown_to_html(body, title)

        print("Publishing to Blogger...")
        publish_post(service, title, html_content, tags, status)


if __name__ == "__main__":
    main()
